package com.nbu.ejournalgroupproject.enums;

public enum TeacherQualificationEnum {
    PERMIT_MATH_TEACHING,
    PERMIT_NATIVE_LANGUAGE,
    PERMIT_HISTORY_TEACHING,
    PERMIT_GEOGRAPHY_TEACHING,
    PERMIT_PHYSICAL_TEACHING,
    PERMIT_ART_TEACHING,
    PERMIT_MUSIC_TEACHING,
    PERMIT_FOREIGN_LANGUAGE_TEACHING,
    PERMIT_LITERATURE_TEACHING,
    PERMIT_BIOLOGY_TEACHING,
    PERMIT_CHEMISTRY_TEACHING,
    PERMIT_PHYSICS_TEACHING,
    PERMIT_PSYCHOLOGY_TEACHING
}
